import type { CategoryWithProducts } from "@/lib/accessories";

export const STATIC_ACCESSORIES: CategoryWithProducts[] = [
  {
    category: { id: "s1", slug: "charging-cables", name: "Charging Cables", description: "Type 2, CCS & CHAdeMO cables for home and public charging.", icon: "Cable", displayOrder: 1 },
    products: [
      { id: "s1a", categoryId: "s1", categorySlug: "charging-cables", name: "Rolec 7.5m Type 2 Cable", slug: "rolec-type2-75m", description: "7.5-metre tethered Type 2 cable, 32A rated for all UK wallboxes.", brand: "Rolec", priceGbp: 39.99, imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Popular", rating: 4.7, reviewCount: 312, isFeatured: true, compatibleWith: ["EV","PHEV"], displayOrder: 1 },
      { id: "s1b", categoryId: "s1", categorySlug: "charging-cables", name: "Chargemaster CCS Combo Cable", slug: "chargemaster-ccs-combo", description: "50A CCS Combo 2 rapid-charge cable with protective carry bag.", brand: "Chargemaster", priceGbp: 59.99, imageUrl: "https://images.unsplash.com/photo-1611462985358-60d3498e0364?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.5, reviewCount: 148, isFeatured: false, compatibleWith: ["EV"], displayOrder: 2 },
      { id: "s1c", categoryId: "s1", categorySlug: "charging-cables", name: "Granny Charger 10m EVSE", slug: "granny-charger-10m", description: "10-metre Mode 2 cable with UK 3-pin to Type 2 for emergency home charging.", brand: "Pod Point", priceGbp: 49.00, imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "New", rating: 4.3, reviewCount: 94, isFeatured: false, compatibleWith: ["EV","PHEV","Hybrid"], displayOrder: 3 },
    ],
  },
  {
    category: { id: "s2", slug: "home-chargers", name: "Home Chargers", description: "7kW–22kW smart wallbox units for overnight EV charging.", icon: "BatteryCharging", displayOrder: 2 },
    products: [
      { id: "s2a", categoryId: "s2", categorySlug: "home-chargers", name: "Ohme Home Pro 7kW", slug: "ohme-home-pro-7kw", description: "Smart 7kW wallbox with dynamic load balancing and Ohme app control.", brand: "Ohme", priceGbp: 799.00, imageUrl: "https://images.unsplash.com/photo-1625979748130-81b8a1a41b6e?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Popular", rating: 4.8, reviewCount: 524, isFeatured: true, compatibleWith: ["EV","PHEV"], displayOrder: 1 },
      { id: "s2b", categoryId: "s2", categorySlug: "home-chargers", name: "Zappi 7kW Solar EV Charger", slug: "zappi-7kw-solar", description: "Eco-smart charger that prioritises surplus solar energy for charging.", brand: "myenergi", priceGbp: 699.00, imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Hot", rating: 4.7, reviewCount: 390, isFeatured: true, compatibleWith: ["EV","PHEV"], displayOrder: 2 },
      { id: "s2c", categoryId: "s2", categorySlug: "home-chargers", name: "Pod Point Solo 3 7kW", slug: "pod-point-solo3-7kw", description: "OZEV-approved 7kW unit with remote access and load balancing.", brand: "Pod Point", priceGbp: 749.00, imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.5, reviewCount: 280, isFeatured: false, compatibleWith: ["EV","PHEV"], displayOrder: 3 },
    ],
  },
  {
    category: { id: "s3", slug: "battery-covers", name: "Battery Covers", description: "Protective underbody guards and thermal battery wraps.", icon: "Shield", displayOrder: 3 },
    products: [
      { id: "s3a", categoryId: "s3", categorySlug: "battery-covers", name: "Underbody Battery Guard Plate", slug: "underbody-battery-guard", description: "6mm aluminium skid plate protecting HV battery from road debris.", brand: "EV Armor", priceGbp: 129.00, imageUrl: "https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "New", rating: 4.6, reviewCount: 82, isFeatured: true, compatibleWith: ["EV"], displayOrder: 1 },
      { id: "s3b", categoryId: "s3", categorySlug: "battery-covers", name: "Thermal Battery Blanket", slug: "thermal-battery-blanket", description: "Insulating wrap to maintain optimal battery temp in cold UK winters.", brand: "BattWrap", priceGbp: 79.99, imageUrl: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.4, reviewCount: 55, isFeatured: false, compatibleWith: ["EV","PHEV","Hybrid"], displayOrder: 2 },
      { id: "s3c", categoryId: "s3", categorySlug: "battery-covers", name: "Battery Vent Cover Kit", slug: "battery-vent-cover-kit", description: "Seals underbody vents against water ingress during heavy rain or flooding.", brand: "EV Shield", priceGbp: 34.99, imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.2, reviewCount: 41, isFeatured: false, compatibleWith: ["EV","PHEV"], displayOrder: 3 },
    ],
  },
  {
    category: { id: "s4", slug: "portable-chargers", name: "Portable Chargers", description: "Compact emergency chargers — plug into any 3-pin socket.", icon: "Plug", displayOrder: 4 },
    products: [
      { id: "s4a", categoryId: "s4", categorySlug: "portable-chargers", name: "Mustart Level 2 Portable EVSE", slug: "mustart-level2-portable", description: "16A portable charger with adjustable current (8/10/13/16A), 5m cable.", brand: "Mustart", priceGbp: 129.99, imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Popular", rating: 4.6, reviewCount: 204, isFeatured: true, compatibleWith: ["EV","PHEV"], displayOrder: 1 },
      { id: "s4b", categoryId: "s4", categorySlug: "portable-chargers", name: "EVSE UK 3-Pin Mode 2 Charger", slug: "evse-uk-mode2", description: "Standard 3-pin EVSE with in-cable control box, 10A for overnight top-up.", brand: "EVSE UK", priceGbp: 49.99, imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.1, reviewCount: 97, isFeatured: false, compatibleWith: ["EV","PHEV"], displayOrder: 2 },
      { id: "s4c", categoryId: "s4", categorySlug: "portable-chargers", name: "Ratio 22kW Portable Wallbox", slug: "ratio-22kw-portable", description: "22kW 3-phase portable unit for workplaces with CEE socket access.", brand: "Ratio", priceGbp: 349.00, imageUrl: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "New", rating: 4.8, reviewCount: 38, isFeatured: false, compatibleWith: ["EV"], displayOrder: 3 },
    ],
  },
  {
    category: { id: "s5", slug: "aero-accessories", name: "Aero Accessories", description: "Wheel covers, diffusers and spoilers to maximise range.", icon: "Wind", displayOrder: 5 },
    products: [
      { id: "s5a", categoryId: "s5", categorySlug: "aero-accessories", name: "EV Aerocap Wheel Covers Set/4", slug: "ev-aerocap-wheel-covers", description: "Snap-on aero wheel covers reducing drag and extending range by up to 5%.", brand: "AeroCap", priceGbp: 89.99, imageUrl: "https://images.unsplash.com/photo-1622185135505-2d795003994a?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Hot", rating: 4.5, reviewCount: 163, isFeatured: true, compatibleWith: ["EV","PHEV"], displayOrder: 1 },
      { id: "s5b", categoryId: "s5", categorySlug: "aero-accessories", name: "Rear Diffuser Splitter Kit", slug: "rear-diffuser-splitter", description: "Universal rear diffuser improving high-speed stability and aero balance.", brand: "SplitFlow", priceGbp: 64.99, imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.3, reviewCount: 58, isFeatured: false, compatibleWith: ["EV","Hybrid"], displayOrder: 2 },
      { id: "s5c", categoryId: "s5", categorySlug: "aero-accessories", name: "Roof Spoiler Lip (Universal)", slug: "roof-spoiler-lip", description: "Adhesive roof spoiler lip reducing lift and improving EV range efficiency.", brand: "EvoDyn", priceGbp: 49.99, imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.0, reviewCount: 44, isFeatured: false, compatibleWith: ["EV","PHEV","Hybrid"], displayOrder: 3 },
    ],
  },
  {
    category: { id: "s6", slug: "range-monitors", name: "Range Monitors", description: "OBD2 adapters and dashboards for real-time battery insight.", icon: "Gauge", displayOrder: 6 },
    products: [
      { id: "s6a", categoryId: "s6", categorySlug: "range-monitors", name: "LeafSpy Pro OBD2 Adapter", slug: "leafspy-pro-obd2", description: "Bluetooth OBD2 dongle for detailed battery health monitoring via app.", brand: "LeafSpy", priceGbp: 24.99, imageUrl: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Popular", rating: 4.8, reviewCount: 592, isFeatured: true, compatibleWith: ["EV"], displayOrder: 1 },
      { id: "s6b", categoryId: "s6", categorySlug: "range-monitors", name: "CarScanner EV BMS Display", slug: "carscanner-ev-bms", description: "4\" heads-up display showing live SoC, cell balancing and regen data.", brand: "CarScanner", priceGbp: 79.99, imageUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "New", rating: 4.4, reviewCount: 87, isFeatured: false, compatibleWith: ["EV","PHEV"], displayOrder: 2 },
      { id: "s6c", categoryId: "s6", categorySlug: "range-monitors", name: "FIXD EV Sensor & App", slug: "fixd-ev-sensor", description: "OBD2 sensor and app translating fault codes into plain-English explanations.", brand: "FIXD", priceGbp: 19.99, imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.2, reviewCount: 340, isFeatured: false, compatibleWith: ["EV","PHEV","Hybrid"], displayOrder: 3 },
    ],
  },
  {
    category: { id: "s7", slug: "service-kits", name: "EV Service Kits", description: "Tyre inflators, tow straps and breakdown kits for EVs.", icon: "Wrench", displayOrder: 7 },
    products: [
      { id: "s7a", categoryId: "s7", categorySlug: "service-kits", name: "Ring RAC900 Tyre Inflator", slug: "ring-rac900-inflator", description: "Digital 12V tyre inflator with auto-shutoff and LED, ideal for EV frunk storage.", brand: "Ring", priceGbp: 34.99, imageUrl: "https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Popular", rating: 4.7, reviewCount: 815, isFeatured: true, compatibleWith: ["EV","PHEV","Hybrid"], displayOrder: 1 },
      { id: "s7b", categoryId: "s7", categorySlug: "service-kits", name: "EV Breakdown Safety Kit", slug: "ev-breakdown-kit", description: "HV-safe breakdown kit: insulating gloves, triangle, torch and first aid.", brand: "EVSafe", priceGbp: 49.99, imageUrl: "https://images.unsplash.com/photo-1504222490345-c075b626c817?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "New", rating: 4.5, reviewCount: 72, isFeatured: false, compatibleWith: ["EV","PHEV","Hybrid"], displayOrder: 2 },
      { id: "s7c", categoryId: "s7", categorySlug: "service-kits", name: "Heavy-Duty EV Tow Strap 5T", slug: "heavy-duty-tow-strap-5t", description: "5-tonne rated flat tow strap with shackles — EV safe, no snatch loading.", brand: "TowPro", priceGbp: 22.99, imageUrl: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: null, rating: 4.3, reviewCount: 128, isFeatured: false, compatibleWith: ["EV","PHEV","Hybrid"], displayOrder: 3 },
    ],
  },
  {
    category: { id: "s8", slug: "hybrid-gadgets", name: "Hybrid Gadgets", description: "Regen brake optimisers, HV safety gloves and diagnostic tools.", icon: "Zap", displayOrder: 8 },
    products: [
      { id: "s8a", categoryId: "s8", categorySlug: "hybrid-gadgets", name: "Regen Brake Pedal Optimizer", slug: "regen-brake-optimizer", description: "Plug-in module that sharpens regen braking response on compatible hybrids.", brand: "RegenTune", priceGbp: 89.99, imageUrl: "https://images.unsplash.com/photo-1504222490345-c075b626c817?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Hot", rating: 4.5, reviewCount: 63, isFeatured: true, compatibleWith: ["Hybrid","PHEV"], displayOrder: 1 },
      { id: "s8b", categoryId: "s8", categorySlug: "hybrid-gadgets", name: "HV Safety Insulating Gloves", slug: "hv-safety-gloves-class0", description: "Class 0 (1000V) rubber insulating gloves for safe hybrid/EV HV work.", brand: "Salisbury", priceGbp: 44.99, imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "Popular", rating: 4.9, reviewCount: 94, isFeatured: false, compatibleWith: ["EV","PHEV","Hybrid"], displayOrder: 2 },
      { id: "s8c", categoryId: "s8", categorySlug: "hybrid-gadgets", name: "Hybrid Battery Tester Probe", slug: "hybrid-battery-tester", description: "Handheld HV battery state-of-health tester for NiMH and Li-ion hybrid packs.", brand: "Midtronics", priceGbp: 149.00, imageUrl: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=400&h=300&fit=crop&auto=format", affiliateUrl: null, badge: "New", rating: 4.7, reviewCount: 29, isFeatured: false, compatibleWith: ["Hybrid","PHEV"], displayOrder: 3 },
    ],
  },
];
