export const dynamic = "force-dynamic";

import { createAdminClient } from "@/lib/supabase/admin";

type BatteryReport = {
  id: string;
  vin: string;
  brand: string;
  model: string;
  year: number;
  mileage: number;
  soh: number;
  status: string;
  created_at: string;
};

async function getReports(): Promise<BatteryReport[]> {
  const admin = createAdminClient();
  const { data, error } = await admin
    .from("battery_health_reports")
    .select("id, vin, brand, model, year, mileage, soh, status, created_at")
    .order("created_at", { ascending: false })
    .limit(100);

  if (error) {
    console.error("[admin/battery-reports]", error.message);
    return [];
  }
  return (data ?? []) as BatteryReport[];
}

function SohBadge({ soh }: { soh: number }) {
  const color = soh >= 95 ? "text-emerald-700 bg-emerald-50 border-emerald-200"
    : soh >= 88 ? "text-brand bg-brand/8 border-brand/20"
    : soh >= 80 ? "text-amber-700 bg-amber-50 border-amber-200"
    : "text-red-600 bg-red-50 border-red-200";
  return (
    <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-bold ${color}`}>
      {soh}%
    </span>
  );
}

export default async function BatteryReportsAdminPage() {
  const reports = await getReports();

  const counts = {
    total: reports.length,
    excellent: reports.filter((r) => r.soh >= 95).length,
    good: reports.filter((r) => r.soh >= 88 && r.soh < 95).length,
    concern: reports.filter((r) => r.soh < 88).length,
  };

  const revenue = counts.total * 29;

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Battery Health Reports</h1>
        <p className="mt-1 text-sm text-gray-500">
          VIN-level battery diagnostics generated by users. £29 per report.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        {[
          { label: "Total reports",    value: counts.total,     color: "text-gray-900" },
          { label: "Excellent (≥95%)", value: counts.excellent, color: "text-emerald-600" },
          { label: "Good (88–94%)",    value: counts.good,      color: "text-brand" },
          { label: "Concern (<88%)",   value: counts.concern,   color: "text-amber-600" },
        ].map((s) => (
          <div key={s.label} className="rounded-2xl border border-gray-200 bg-white px-5 py-4">
            <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            <p className="mt-1 text-xs text-gray-400">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Revenue */}
      <div className="rounded-2xl border border-brand/20 bg-brand/5 px-5 py-4">
        <p className="text-xs font-semibold uppercase tracking-wider text-brand">Revenue</p>
        <p className="mt-2 text-2xl font-bold text-gray-900">£{revenue.toLocaleString()}</p>
        <p className="mt-1 text-xs text-gray-500">
          {counts.total} reports × £29 · Target: 600 reports/mo = £17,400/mo
        </p>
      </div>

      {reports.length === 0 ? (
        <div className="rounded-2xl border border-gray-200 bg-gray-50 py-12 text-center">
          <p className="text-gray-500">No reports yet.</p>
          <p className="mt-1 text-xs text-gray-400">Reports appear here once users generate them at /battery-health</p>
        </div>
      ) : (
        <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50">
                  {["VIN", "Vehicle", "Mileage", "Battery SOH", "Generated"].map((h) => (
                    <th key={h} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {reports.map((r) => (
                  <tr key={r.id} className="transition hover:bg-gray-50">
                    <td className="px-4 py-3 font-mono text-xs text-gray-500">{r.vin}</td>
                    <td className="px-4 py-3">
                      <p className="font-semibold text-gray-900">{r.year} {r.brand} {r.model}</p>
                    </td>
                    <td className="px-4 py-3 text-gray-600">{r.mileage.toLocaleString()} mi</td>
                    <td className="px-4 py-3"><SohBadge soh={r.soh} /></td>
                    <td className="px-4 py-3 text-xs text-gray-400">
                      {new Date(r.created_at).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
