export const dynamic = "force-dynamic";

import { createAdminClient } from "@/lib/supabase/admin";

type BatteryReport = {
  id: string;
  vin: string;
  brand: string;
  model: string;
  year: number;
  mileage: number;
  soh: number;
  status: string;
  created_at: string;
};

async function getReports(): Promise<BatteryReport[]> {
  const admin = createAdminClient();
  const { data, error } = await admin
    .from("battery_health_reports")
    .select("id, vin, brand, model, year, mileage, soh, status, created_at")
    .order("created_at", { ascending: false })
    .limit(100);

  if (error) {
    console.error("[admin/battery-reports]", error.message);
    return [];
  }
  return (data ?? []) as BatteryReport[];
}

function SohBadge({ soh }: { soh: number }) {
  const color = soh >= 95 ? "text-emerald-400 bg-emerald-500/8 border-emerald-500/20"
    : soh >= 88 ? "text-brand bg-brand/8 border-brand/20"
    : soh >= 80 ? "text-amber-400 bg-amber-500/8 border-amber-500/20"
    : "text-red-400 bg-red-500/8 border-red-500/20";
  return (
    <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-bold ${color}`}>
      {soh}%
    </span>
  );
}

export default async function BatteryReportsAdminPage() {
  const reports = await getReports();

  const counts = {
    total: reports.length,
    excellent: reports.filter((r) => r.soh >= 95).length,
    good: reports.filter((r) => r.soh >= 88 && r.soh < 95).length,
    concern: reports.filter((r) => r.soh < 88).length,
  };

  const revenue = counts.total * 29;

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-white">Battery Health Reports</h1>
        <p className="mt-1 text-sm text-white/50">
          VIN-level battery diagnostics generated by users. £29 per report.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        {[
          { label: "Total reports",   value: counts.total,     color: "text-white" },
          { label: "Excellent (≥95%)", value: counts.excellent, color: "text-emerald-400" },
          { label: "Good (88–94%)",    value: counts.good,      color: "text-brand" },
          { label: "Concern (<88%)",   value: counts.concern,   color: "text-amber-400" },
        ].map((s) => (
          <div key={s.label} className="rounded-2xl border border-white/8 bg-white/[0.04] px-5 py-4">
            <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            <p className="mt-1 text-xs text-white/40">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Revenue */}
      <div className="rounded-2xl border border-brand/20 bg-brand/5 px-5 py-4">
        <p className="text-xs font-semibold uppercase tracking-wider text-brand">Revenue</p>
        <p className="mt-2 text-2xl font-bold text-white">£{revenue.toLocaleString()}</p>
        <p className="mt-1 text-xs text-white/50">
          {counts.total} reports × £29 · Target: 600 reports/mo = £17,400/mo
        </p>
      </div>

      {reports.length === 0 ? (
        <div className="rounded-2xl border border-white/8 bg-white/[0.03] py-12 text-center">
          <p className="text-white/40">No reports yet.</p>
          <p className="mt-1 text-xs text-white/25">Reports appear here once users generate them at /battery-health</p>
        </div>
      ) : (
        <div className="overflow-hidden rounded-2xl border border-white/8">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/8 bg-white/[0.03]">
                  {["VIN", "Vehicle", "Mileage", "Battery SOH", "Generated"].map((h) => (
                    <th key={h} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-white/30">
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-white/[0.05]">
                {reports.map((r) => (
                  <tr key={r.id} className="transition hover:bg-white/[0.02]">
                    <td className="px-4 py-3 font-mono text-xs text-white/60">{r.vin}</td>
                    <td className="px-4 py-3">
                      <p className="font-semibold text-white">{r.year} {r.brand} {r.model}</p>
                    </td>
                    <td className="px-4 py-3 text-white/70">{r.mileage.toLocaleString()} mi</td>
                    <td className="px-4 py-3"><SohBadge soh={r.soh} /></td>
                    <td className="px-4 py-3 text-xs text-white/40">
                      {new Date(r.created_at).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
